### ISSUE TITLE
启动时无法加载application.yml 中的properties

### ISSUE THREAD

**Issue by forestkeeper** [Wechat-Group/weixin-java-mp-demo-springboot#5]
按照readme配置完application.yml 中的propertes并启动后，application.yml 中appid 等几个配置都加载为null

**Comment by binarywang** [comment]
你是否格式不对，请检查核实一下

**Comment by ruanlinjing** [comment]
我也遇到此问题.很奇怪.就是加载未null.格式是复制application.yml.template里面的.就填写了下自己的相关appid什么的.但就是加载null.

**Comment by forestkeeper** [comment]
格式是正确的，打了断点检查，确实@Configuration 里面的配置都没有加载进去

**Comment by binarywang** [comment]
是不是属性后的内容前没加空格

**Comment by binarywang** [comment]
@forestkeeper @ruanlinjing 我测试过了，没猜错的话就是我说的那个问题，现在已经在readme文件里做了说明。

**Comment by wqlm** [comment]
![image](https://cloud.githubusercontent.com/assets/21995894/26619597/bba04fd2-4611-11e7-80e5-dcdcb1d33f0e.png)
![image](https://cloud.githubusercontent.com/assets/21995894/26619636/e7b786a8-4611-11e7-81bc-0f228bee1b2c.png)
yam里面的keyPath不能使用classPath的写法的话，部署服务器后 keyPath 应该怎么填？？？

**Comment by binarywang** [comment]
写完整路径吧

**Comment by linkebin** [comment]
我也遇到这个问题  不是空格的原因

**Comment by binarywang** [comment]
不是空格原因，那就是其他原因，你找到原因了？试图调试过没

**Comment by binarywang** [comment]
每个字符存在都是有原因的，不了解的话可能不能乱删
