### ISSUE TITLE
怎么启动 com.github.binarywang.demo.wechat.WxMpDemoApplication ？

### ISSUE THREAD

**Issue by shamoman** [Wechat-Group/weixin-java-mp-demo-springboot#6]
几个基本的小问题：
1. 启动部署整个过程可以详细点吗？还不是很明白怎么运行程序！
2. ngrok 目录在哪？

**Comment by binarywang** [comment]
1.  这是个java程序，直接运行即可;
2. ngrok在根目录下。
建议先了解下spring boot的基本知识，如果觉得麻烦可以使用其他demo
