### ISSUE TITLE
运行时报错“请求参数非法，请核实！”

### ISSUE THREAD

**Issue by ziyitony** [Wechat-Group/weixin-java-mp-demo-springboot#7]
首先非常感谢作者的辛苦工作，我尝试了一下，看了前面两个issue，避开细节坑成功部署。
我使用的是微信公众平台的测试号来进行测试运行的。
（http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login）

但是实际运行的时候抛出“请求参数非法，请核实！”异常，并不影响功能，只是看着心惊胆战。
查看了一下日志，似乎是微信服务器会在处理完一条消息之后就发一个空消息过来。请问这个是微信服务器自己发过来的心跳包还是什么异常？

![tim 20170630170037](https://user-images.githubusercontent.com/18106851/27728951-77ee60e6-5db6-11e7-8dc7-de20e7298add.png)

![default](https://user-images.githubusercontent.com/18106851/27728952-7abdfc00-5db6-11e7-95e4-6733bb08a30c.png)

**Comment by binarywang** [comment]
参数为空了，微信服务器发过来的参数不可能为空，这一点你要明白

**Comment by ziyitony** [comment]
我又测试了一下，普通交互的时候不会报错，只在微信认证我服务器接口配置信息的时候会报错。可能是网络不通畅或者什么别的原因吧。

**Comment by ziyitony** [comment]
@binarywang 好的，我多测试看看，还是非常感谢你的demo！

**Comment by ziyitony** [comment]
@binarywang 确实没问题，应该是我前面的操作出错了
