### ISSUE TITLE
WxMenuController的/getSelfMenuInfo报错

### ISSUE THREAD

**Issue by supreme94** [Wechat-Group/weixin-java-mp-demo-springboot#8]
错误信息：
exception=org.springframework.http.converter.HttpMessageNotWritableException, message=Could not write JSON: No serializer found for class me.chanjar.weixin.mp.bean.menu.WxMpSelfMenuInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class me.chanjar.weixin.mp.bean.menu.WxMpSelfMenuInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: me.chanjar.weixin.mp.bean.menu.WxMpGetSelfMenuInfoResult["selfMenuInfo"]), path=/wechat/menu/getSelfMenuInfo, URL=http://****.tunnel.echomod.cn/error}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@7da87440]

**Comment by binarywang** [comment]
是jackson的问题，将其排除就好了，使用默认的gson

**Comment by supreme94** [comment]
@binarywang 
嗯，JsonUtils的代码改成下面能正确返回

```
public class JsonUtils {
	private static final Gson gson = new GsonBuilder().disableHtmlEscaping().create();

	public static String toJson(Object obj) {
		
		return gson.toJson(obj);

	}
}
```
